### ISSUE TITLE
Support `azcliversion`

### ISSUE THREAD

**Issue by jiasli** [Azure/login#164]
[Azure CLI Action](https://github.com/marketplace/actions/azure-cli-action) supports `azcliversion`:

https://github.com/Azure/cli/blob/master/src/main.ts#L25

```ts
let azcliversion: string = core.getInput('azcliversion', { required: true }).trim().toLowerCase();
```

In case of Azure CLI compatibility issue or bug, it is possible to revert to old versions of Azure CLI.

But, [Azure Login](https://github.com/marketplace/actions/azure-login) doesn't have `azcliversion`: https://github.com/Azure/login/blob/master/src/main.ts

**In case of `az login` compatibility issue or bug, there is no way for Azure Login to recover.**

Related issues: 

- https://github.com/Azure/login/issues/162
- https://github.com/Azure/azure-cli/issues/20154

**Comment by restfulhead** [comment]
Yes, I hope this requests gets priority. I came here from https://github.com/Azure/cli/issues/56#issuecomment-968579245 where builds started to fail one day without any changes on our end. We need to be able to pin the version to guarantee stable builds...

**Comment by Menci** [comment]
There's a workaround that invokes `az login` in `azure/CLI` action:

```yaml
    - uses: azure/CLI@v1
      with:
        azcliversion: 2.28.0
        inlineScript: |
          AZ_PYTHON_PARSE_CODE='import sys, re; s = "".join(sys.stdin.readlines()); data = {a: b for a, b in [x.split(":") for x in re.sub("[\s\"]", "", s)[1:-1].split(",")]}'

          AZ_CLIENT_ID="$(python3 -c "$AZ_PYTHON_PARSE_CODE; print(data['clientId'])" <<< "$AZ_CRED")"
          AZ_CLIENT_SECRET="$(python3 -c "$AZ_PYTHON_PARSE_CODE; print(data['clientSecret'])" <<< "$AZ_CRED")"
          AZ_SUBSCRIPTION_ID="$(python3 -c "$AZ_PYTHON_PARSE_CODE; print(data['subscriptionId'])" <<< "$AZ_CRED")"
          AZ_TENANT_ID="$(python3 -c "$AZ_PYTHON_PARSE_CODE; print(data['tenantId'])" <<< "$AZ_CRED")"

          az login --service-principal -u "$AZ_CLIENT_ID" -p "$AZ_CLIENT_SECRET" --tenant "$AZ_TENANT_ID"
          az account set --subscription "$AZ_SUBSCRIPTION_ID"
      env:
        AZ_CRED: ${{ secrets.creds }}
```

You can also use it in a composite action like [this](https://github.com/Menci/deploy-certificate-to-azure-web-app/blob/da83dcefba4a93b8557cd8ec050fdab97665d15e/action.yml#L38).

Parsing `creds` with Python since passing it to a composite action will lose double quotes (`{"a": "b"}` turns to `{a: b}`) in the string.

**Comment by cperfect** [comment]
Also would resolve https://github.com/microsoft/azure-container-apps/issues/28

**Comment by NissesSenap** [comment]
Ping

**Comment by NissesSenap** [comment]
Pong

**Comment by BALAGA-GAYATRI** [comment]
Here the issue is when there is a compact issue that arises when a workflow uses both CLI and azure login actions. So if the cli latest is incompatible with the cli from the runner, workflows might fail.  In order to avoid this issue, CLI action now implements a new strategy that checks for the runner CLI version and defaults to it unless an explicit version is provided in `azcliversion`. So that would solve the above concern.
More details - https://github.com/azure/cli#github-action-for-azure-cli

**Comment by NissesSenap** [comment]
@BALAGA-GAYATRI I'm going to be rather honest in this but i don't understand the solution. 

Using the Azure CLI GitHub action is a know workaround and something that all of us had to apply when Microsoft did this breaking change without releasing a major version. See: 
https://github.com/Azure/login/issues/164#issuecomment-980537173

We don't want to use this workaround, the whole point of this GitHub action is to login. 

How does this help us in this GitHub action? If you have some magic in this GitHub action please document it in this action and don't point to the Azure CLI GitHub action. Also please provide a link to the PR where this was implemented.

**Comment by BALAGA-GAYATRI** [comment]
Hey @NissesSenap 
#### Main reason for raising the issue:
So when az-cli came up with a new version using  MSAL removing ADAL, it basically changed the way credentials are stored in the machine. So at that time users having both these actions (i.e, `azure/login` and `azure/cli`) in their workflows faced an  issue because previously `azcliversion`  variable defaulted to `latest` which is latest MSAL and our login action used the cli which is present in the runner. This caused the compat issue. Now `azure/cli` action's `azcliversion` defaults to the runner cli if not specified. This will prevent the compat issues in future. Coming to `azure/login` action , the current design doesn't include this `azcliversion` implementation and may be implemented in future but can't promise to have this any time soon. Hope this answered your question. Thanks.

**Comment by NissesSenap** [comment]
I know, i have spent allot of time working around this issue.
Isn't the whole point of this issue that we want support for azcliversion? So the next time Azure decide to do a breaking change without making major release we can work around it by defining the azcliversion so we don't have to use the ugly workaround and actually be able to use the login GitHub action.

To me it makes sense to keep this issue open until the issue is solved. How else will keep track of it?

**Comment by NissesSenap** [comment]
Another option could be that you say that it will never be implemented and then we know that at least :)
