### ISSUE TITLE
Alternative for --sdk-auth for login action

### ISSUE THREAD

**Issue by ninallam** [Azure/login#223]
I am from Azure Load Testing team and our action has a dependency on Azure Login action. Our customers have raised an [issue](https://github.com/MicrosoftDocs/azure-docs/issues/92827) that Azure CLI has deprecated `--sdk-auth` from `az ad sp create-for-rbac` and our docs need to be updated accordingly. Can you suggest an alternative for this which would be compatible with the login action?

**Comment by BALAGA-GAYATRI** [comment]
Hi @ninallam So this deprecation is not yet done. This is on hold due to its consumption in azure actions. We have updated our docs also about the same.
> Note: The above az ad sp create-for-rbac command will give you the --sdk-auth deprecation warning. As we are working with CLI for this deprecation process, we strongly recommend users to use this --sdk-auth flag as the result dictionary output changes and not accepted by login action if --sdk-auth is not used. 

[Ref ⬆️ ](https://github.com/Azure/login#configure-a-service-principal-with-a-secret)
So you can use it and should be working fine for now. However there is also[ OIDC login mechanism](https://github.com/Azure/login#configure-a-service-principal-with-a-federated-credential-to-use-oidc-based-authentication) that is supported in this action which doesn't require `az ad sp create-for-rbac` for sp creation.
Since we are tracking this `--sdk-auth` deprecation [here](https://github.com/Azure/login/issues/190), we are closing this issue as it is a duplicate. Thank you.
