### ISSUE TITLE
locked down runner az cli dependecy

### ISSUE THREAD

**Issue by Lavaerius** [Azure/login#301]
I have runner that are reasonably locked down, that don't come with the azure cli installed.

Can I use the azure CLI action as a dependency to run the azure/login action or do I have to build the runner fresh with az already installed ahead of time?

I've seen this issue:  https://github.com/Azure/login/issues/295

and I'm unsure if my inability to login is due to whatever happened to their creds, or the inability to leverage the azure cli action to satisfy the requirement

Thanks.

**Comment by BALAGA-GAYATRI** [comment]
Can you try adding this step and let m know if it's helping in installing az cli?
``` 
- name: Installing CLI-beta for OIDC
   run: |
            python3 -m pip install -q --upgrade pip
            pip install azure-cli
```

**Comment by MoChilia** [comment]
Hi @Lavaerius,

The `azure/cli` action **cannot** be used as a dependency to run the `azure/login` action.

Since the `azure/cli` action runs on the docker container with preinstalled `az cli`, it will not install `az cli` on your runner. Once you finish the `azure/cli` action, it will clean up the container. You should install `az cli` on your runner before using `azure/login`. We don't recommend use `azure/cli` before `azure/login`. The standard operation to run any Azure actions is to perform the login action first. You may find an available way to install `az cli` in https://learn.microsoft.com/en-us/cli/azure/install-azure-cli. 

I am not sure what does "locked down" mean. If your runner cannot install any dependency globally, maybe you can leverage the `azure/cli` action to login. Just try to run `az login` in the `inlineScript` of `azure/cli`.

**Comment by MoChilia** [comment]
Closing the issue, since the workaround was provided and there are no further requests from the author.
