### ISSUE TITLE
Allow to specify custom subject for federated login

### ISSUE THREAD

**Issue by tobiasdiez** [Azure/login#346]
If you login using OIDC, the subject for the federated login is automatically generated based on the github context. However, sometimes it is convenient to provide a custom subject, e.g. if you want to support pushes to arbitrary branches (and not only exactly one branch).

**Comment by MoChilia** [comment]
Hi @tobiasdiez,
Allow me to clarify your inquiry:

- If you want to push to arbitrary branches, not only exactly one branch, then you can customize the subject of the federated credential to [filter for a specific environment](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#filtering-for-a-specific-environment) to have access to the whole repo. 
- If you want to use OIDC in a workflow triggered by pull requests, then you can try [filtering for pull_request events](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#filtering-for-pull_request-events). 
- Detailed instructions on how to customize the subject of the federated credential can be found in [Configure a federated identity credential on an app](https://learn.microsoft.com/azure/active-directory/workload-identities/workload-identity-federation-create-trust?pivots=identity-wif-apps-methods-azp). 

The login action's role is to verify whether the current subject aligns with the subject configured for your federated credential. It's the subject of your federated credential that should be updated, not customizing the subject on the login action side. Feel free to correct me if I've misconstrued your request.

**Comment by tobiasdiez** [comment]
Thanks for your reply!

I would like to push to arbitrary branches in the repo, yes. However, we are already using environments (for a different purpose), so that's not really an option. Similarly, the pull_request event is also not helpful since the workflow should be triggered manually using `workflow_dispatch`. AWS allows to match the subject using wildcards but this doesn't seem to work with azure. Thus my idea was to specify a custom subject (e.g. myrepo/workflowname/workflow_dispatch) and register this subject in the azure portal.

**Comment by MoChilia** [comment]
I see. You want to grant the federated token to workflows across various branches within the repository. However, due to certain constraints, utilizing an environment is not feasible. Instead, you intend to utilize wildcards to define the subject, such as `repo:MY_ORG/MY_REPO:*`. However, as far as I know, Azure workload identity doesn't currently support this type of OIDC claim. I recommend you submit the feature request in https://github.com/Azure/azure-workload-identity.

**Comment by tobiasdiez** [comment]
okay, I've opened https://github.com/Azure/azure-workload-identity/issues/1118 for this. However, I do think it should be possible to set a custom subject (for example in scenarios using workflow_dispatch which depending on the workflow can have quite a few different meanings)

**Comment by illrill** [comment]
I would also like a configuration option to specify which subject should be used.

I have a user-assigned managed identity configured with a branch federation subject `repo:<org>/<repo>:ref:refs/heads/main`. This works when the workflow job **doesn't** reference any Github environment. However as soon as the job references a Github environment (for other reasons, e.g. getting environment variables), the azure/login action automatically sets the subject `repo:<org>/<repo>:environment:<environment>` (for which I don't have any federation), and it breaks.

Being able to configure the subject would allow me to use the branch federation **and** still reference an environment in my workflow job (for other reasons than authentication).

**Comment by MoChilia** [comment]
Hi @illrill,
Currently, azure/login only supports managed identities with federated credentials. Please note that managed identities without federation are still in development (#348). Therefore, if you haven't configured federated credentials for the managed identity, azure/login will fail to fetch the federated token. 
However, you've brought out a good point. It is reasonable to use branch federation while referencing an environment. I will keep looking into what can be done in azure login action.

**Comment by YanaXu** [comment]
Hi @tobiasdiez, Azure Login Action relies on [OIDC Token](https://github.com/actions/toolkit/tree/main/packages/core#oidc-token). It's the official method to get the OIDC Token provided by GitHub. 
The way to "customize" a subject is extremely insecure. That means anyone can "fake" the subject and use it wherever they want.

**Comment by YanaXu** [comment]
> I would also like a configuration option to specify which subject should be used when logging in.
> 
> In my scenario, I have a user-assigned managed identity configured with a branch federation subject `repo:<org>/<repo>:ref:refs/heads/main`. This is my workflow:
> 
> ```
> name: deployment
> on:
>   push:
>     branches:
>       - main
> permissions:
>   id-token: write
>   contents: read
> jobs:
>   deployment:
>     runs-on: ubuntu-latest
>     environment: production
>     steps:
>       - uses: actions/checkout@v4
>       - uses: azure/login@v1
>         with:
>           client-id: ***
>           subscription-id: ***
>           tenant-id: ***
> ```
> 
> Login only works if the workflow job **doesn't** reference any Github environment. However, if the workflow job references a Github environment (for other reasons, e.g. variables and secrets), the login action automatically sets the subject `repo:<org>/<repo>:environment:production` (for which I don't have any federated credential), and it breaks.
> 
> Being able to configure the subject would allow me to use the branch federation **and** still reference an environment in my workflow job (for other reasons than authentication).

Hi @illrill, I think it's a valid requirement. However, it's beyond the scope of Azure Login Action. 
Azure Login Action relies on GitHub generated [OIDC Token](https://github.com/actions/toolkit/tree/main/packages/core#oidc-token).
Azure Login Action call GitHub to generate the OIDC token and send the token to Azure.
You can refer to one token example: [Understanding the OIDC token](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#understanding-the-oidc-token).
You see, the OIDC token generated by GitHub contains not only **sub**, but also **repository**(org and repo) and **ref**(repo branch).
It depends on the talk between GitHub and Azure. Azure Login Action can't change the content of the OIDC token or fake it. Azure Login Action can't make Azure to read **ref** instead of **sub**. 
Therefore, It's better to raise a question or feature request to GitHub or Azure.

**Comment by tobiasdiez** [comment]
Thanks for looking at this @YanaXu!

I'm a bit confused why this shouldn't be possible from a security viewpoint. Of course, you cannot allow arbitrary modifications, but it sounds reasonable that the `claims` that are already present in the JWT can be written to the `sub` in a customizable way. In fact, github supports this already: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#customizing-the-subject-claims-for-an-organization-or-repository https://docs.github.com/en/rest/actions/oidc?apiVersion=2022-11-28#about-github-actions-oidc on a repo/org level.

So it might be possible to send the `include_claims` specification when asking for the JWT token. I couldn't find much information about this (and it might require work in `toolkit`), but I'm sure you can inquire about this internally.

**Comment by YanaXu** [comment]
Hi @tobiasdiez , there are 3 participators: GitHub, Azure, Login Action. 
Only GitHub can "write" the token, Login Action can only apply for the token. What you said in the last comment is correct but only GitHub can do it, not Login Action.
The only parameter Login Action (or other clients on GitHub) can change is "aud", which is hardcoded in Azure in our case.
![image](https://github.com/Azure/login/assets/12843157/4d2ee1f9-4c25-422a-9c9b-58ec683fb9dc)

If Login Action can change the OIDC token generated by GitHub, that means anyone can write a similar piece of code to "fake" a token in only local env (without GitHub at all). If they use the "fake" token to talk with Azure, what would happen? That's why it's insecure if Login Action can change the token content.

**Comment by petr-stupka** [comment]
@YanaXu 

The answer is here:

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect

Here the claim will include only the repo name (no branch, no environment) and anything else is ignored

```bash
gh api --method PUT \
-H "Accept: application/vnd.github+json" \
-H "X-GitHub-Api-Version: 2022-11-28" \
/repos/{owner}/{repo}/actions/oidc/customization/sub \
-F use_default=false \
-f "include_claim_keys[]=repo"
```
