### ISSUE TITLE
Federated credential subject claim in workflow does not match subject found on user-assigned managed identity

### ISSUE THREAD

**Issue by yoonaoh** [Azure/login#379]
Hi! I'm running a [workflow file](https://github.com/yoonaoh/github-action-testfunctionapp-java/actions/runs/7053479320/job/19200720003), and I keep running into this error: 

`Error: AADSTS700213: No matching federated identity record found for presented assertion subject 'repo:yoonaoh/github-action-testfunctionapp-java:ref:refs/heads/master'. Please check your federated identity credential Subject, Audience and Issuer against the presented assertion
`

When I check the Subject identifier on my managed identity's federated credential, however, I have it set to this `repo:yoonaoh/github-action-testfunctionapp-java:environment:test-slot`. 

Not sure where this discrepancy is coming from, or how the action is finding the subject.

**Comment by YanaXu** [comment]
Hi @yoonaoh , in your screenshot, you configure the entity type as `environment`. But in your workflow file, you didn't use environment. That's why GitHub generate `branch` token for you. You have to update your workflow file and use "environment". You can refer to an example [here](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#using-an-environment).
