### ISSUE TITLE
GitHub Actions Large Runner OIDC with Managed identity

### ISSUE THREAD

**Issue by phoang-AmeriCorps** [Azure/login#445]
We're using GitHub Large runner and static IP range that is whitelisted on Azure Firewall and Network configurations. However, User Managed Identity doesn't recognize GitHub larger runner IP addresses.

**Comment by YanaXu** [comment]
Hi @phoang-AmeriCorps, I thinks this question is not for Azure Login Action but for Azure.
Azure Login Action only leverages the features provided by Azure. That means, if you can use User Managed Identity to login Azure on your "GitHub Large runner" somehow, you can use it in Azure Login Action, otherwise no.

**Comment by phoang-AmeriCorps** [comment]
How's about the notes below in README.md file.

![image](https://github.com/Azure/login/assets/160646938/68eea7a4-9bd1-41d5-a8cf-dcf65dc13f55)

**Comment by YanaXu** [comment]
Do you mean your "GitHub Large runner" are hosted by Azure VM?

**Comment by phoang-AmeriCorps** [comment]
Correct, we're using GitHub Large Runner hosted by GitHub

**Comment by YanaXu** [comment]
Hi @phoang-AmeriCorps , as I know, a runner hosted by GitHub do not support Managed Identity login to Azure. Please correct me if I'm wrong. And if I'm wrong, please lead me to the right guide that I can refer to.

**Comment by YanaXu** [comment]
I'll close this issue since no feedback from author for a long time. Feel free to reopen it.
