### ISSUE TITLE
Can I call az login CLI command instead of azure/login@v1?

### ISSUE THREAD

**Issue by AllanXu49** [Azure/login#88]
In my GitHub workflow, can I call az login CLI command instead of azure/login@v1?

If yes, then what is the advantage of azure/login@v1 over Azure CLI login?

Thank you,

**Comment by arjgupta** [comment]
@AllanXu49 yes you can always directly run az login commands in your scripts in your workflow. With the login action, you get the advantage of logging in for both az cli and azure powershell and handling secrets. Also, if az login changes it's api, we will update the action to use the new api. If otherwise you are using a custom script to run az login, then you will need to handle these on your own.
